#!/bin/sh

cat <<EOF > .env
# DB
DATABASE_CONNECTION = "${DATABASE_CONNECTION}"
DATABASE_HOST = "${DATABASE_HOST}"
DATABASE_PORT = "${DATABASE_PORT}"
DATABASE_USERNAME = "${DATABASE_USERNAME}"
DATABASE_PASSWORD = "${DATABASE_PASSWORD}"
DATABASE_DATABASE = "${DATABASE_DATABASE}"
DATABASE_SCHEMA = "${DATABASE_SCHEMA}"
DATABASE_SYNCHRONIZE = "${DATABASE_SYNCHRONIZE}"
DATABASE_DROP_SCHEMA = "${DATABASE_DROP_SCHEMA}"
DATABASE_MIGRATIONS_RUN = "${DATABASE_MIGRATIONS_RUN}"
DATABASE_LOGGING = "${DATABASE_LOGGING}"
DATABASE_CACHE = "${DATABASE_CACHE}"

# Redis
REDIS_HOST = "${REDIS_HOST}"
REDIS_PORT = "${REDIS_PORT}"
REDIS_DB = "${REDIS_DB}"
REDIS_PASSWORD = "${REDIS_PASSWORD}"
REDIS_PREFIX = "${REDIS_PREFIX}"

# App
HOST = "${HOST}"
PORT = "${PORT}"
PORT_DEBUGGER = "${PORT_DEBUGGER}"
SESSION_SECRET = "${SESSION_SECRET}"

# LDAP
LDAP_URL = "${LDAP_URL}"
LDAP_BIND_DN = "${LDAP_BIND_DN}"
LDAP_BIND_PW = "${LDAP_BIND_PW}"
LDAP_SEARCH_BASE = "${LDAP_SEARCH_BASE}"
LDAP_SEARCH_FILTER = "${LDAP_SEARCH_FILTER}"
EOF
