#!/bin/sh

cat <<EOF > .env
# App
HOST="${HOST}"
PORT="${PORT}"
PORT_DEBUGGER="${PORT_DEBUGGER}"

# DB
DATABASE_CONNECTION="${DATABASE_CONNECTION}"
DATABASE_HOST="${DATABASE_HOST}"
DATABASE_PORT="${DATABASE_PORT}"
DATABASE_USERNAME="${DATABASE_USERNAME}"
DATABASE_PASSWORD="${DATABASE_PASSWORD}"
DATABASE_DATABASE="${DATABASE_DATABASE}"
DATABASE_SCHEMA="${DATABASE_SCHEMA}"
DATABASE_SYNCHRONIZE="${DATABASE_SYNCHRONIZE}"
DATABASE_DROP_SCHEMA="${DATABASE_DROP_SCHEMA}"
DATABASE_MIGRATIONS_RUN="${DATABASE_MIGRATIONS_RUN}"
DATABASE_LOGGING="${DATABASE_LOGGING}"
DATABASE_CACHE="${DATABASE_CACHE}"

# HTTP Redis
HTTP_REDIS_HOST="${HTTP_REDIS_HOST}"
HTTP_REDIS_PORT="${HTTP_REDIS_PORT}"
HTTP_REDIS_DB="${HTTP_REDIS_DB}"
HTTP_REDIS_PASSWORD="${HTTP_REDIS_PASSWORD}"
HTTP_REDIS_PREFIX="${HTTP_REDIS_PREFIX}"
HTTP_REDIS_TTL="${HTTP_REDIS_TTL}"
HTTP_REDIS_MAX_OBJECTS="${HTTP_REDIS_MAX_OBJECTS}"

# LDAP Redis
LDAP_REDIS_HOST="${LDAP_REDIS_HOST}"
LDAP_REDIS_PORT="${LDAP_REDIS_PORT}"
LDAP_REDIS_DB="${LDAP_REDIS_DB}"
LDAP_REDIS_PASSWORD="${LDAP_REDIS_PASSWORD}"
LDAP_REDIS_TTL="${LDAP_REDIS_TTL}"

# Session Redis
SESSION_SECRET="${SESSION_SECRET}"
SESSION_REDIS_HOST="${SESSION_REDIS_HOST}"
SESSION_REDIS_PORT="${SESSION_REDIS_PORT}"
SESSION_REDIS_DB="${SESSION_REDIS_DB}"
SESSION_COOKIE_TTL="${SESSION_COOKIE_TTL}"

# LDAP
LDAP_URL="${LDAP_URL}"
LDAP_BIND_DN="${LDAP_BIND_DN}"
LDAP_BIND_PW="${LDAP_BIND_PW}"
LDAP_SEARCH_BASE="${LDAP_SEARCH_BASE}"
LDAP_SEARCH_FILTER="${LDAP_SEARCH_FILTER}"
EOF

export NODE=`which node`

if [ -n "$*" -a "$1" = "test" ]; then
  export NODE_ENV=${NODE_ENV:=test}
  node_modules/.bin/jest $2 $3 $4 $5
elif [ -n "$*" -a "$1" = "start" ]; then
  export NODE_ENV=${NODE_ENV:=production}
  $NODE .nest/server/main.js
fi
